import React, { useState, useRef, useEffect } from 'react';
import { Company } from '../types';
import { motion, AnimatePresence } from 'motion/react';
import { 
  MessageSquare, 
  Send, 
  X, 
  Bot, 
  User, 
  Sparkles, 
  Scale, 
  AlertCircle,
  HelpCircle,
  ChevronDown
} from 'lucide-react';

interface StatutoryChatProps {
  company: Company;
}

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export default function StatutoryChat({ company }: StatutoryChatProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [errorDetails, setErrorDetails] = useState<string | null>(null);
  
  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Pre-baked helpful statutory queries
  const SUGGESTIONS = [
    "What is the penalty for late AGM under Section 81?",
    "Does our company meet auditor rules?",
    "Explain Section 119 filing of Annual Returns.",
    "Is our company at risk of strike-off?"
  ];

  // Auto-scroll on new message
  useEffect(() => {
    if (bottomRef.current) {
      bottomRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, isTyping]);

  // Focus on input when opened
  useEffect(() => {
    if (isOpen && inputRef.current) {
      setTimeout(() => inputRef.current?.focus(), 250);
    }
  }, [isOpen]);

  const handleSendMessage = async (text: string) => {
    if (!text.trim()) return;
    
    const userMsg: ChatMessage = {
      role: 'user',
      content: text,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setMessages((prev) => [...prev, userMsg]);
    setInputValue('');
    setIsTyping(true);
    setErrorDetails(null);

    try {
      const response = await fetch('/api/gemini/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          company,
          history: messages.map(m => ({ role: m.role, content: m.content })),
          message: text
        })
      });

      const data = await response.json();

      if (!response.ok) {
        if (data.error === "API_KEY_MISSING") {
          setErrorDetails("GEMINI_API_KEY is not defined. Ask the administrator to add it under Settings > Secrets.");
        } else {
          setErrorDetails(data.message || "An error occurred while linking with statutory database.");
        }
        setIsTyping(false);
        return;
      }

      const assistantMsg: ChatMessage = {
        role: 'assistant',
        content: data.response || "No reply was generated by the compliance engine.",
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };

      setMessages((prev) => [...prev, assistantMsg]);
    } catch (err: any) {
      console.error("Chat fetch failure:", err);
      setErrorDetails("Unable to contact the corporate AI API server.");
    } finally {
      setIsTyping(false);
    }
  };

  // Helper function to render simple inline formatting (Bold and code snippets)
  const renderInlineFormatting = (text: string) => {
    const parts = text.split(/(\*\*.*?\*\*|`.*?`)/g);
    return parts.map((part, index) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={index} className="text-white font-bold">{part.slice(2, -2)}</strong>;
      }
      if (part.startsWith('`') && part.endsWith('`')) {
        return (
          <code key={index} className="bg-slate-950 px-1 py-0.5 rounded font-mono text-[10px] text-teal-400 border border-slate-800">
            {part.slice(1, -1)}
          </code>
        );
      }
      return part;
    });
  };

  // Format full message lines beautifully supporting lists and headers
  const formatMessageContent = (text: string) => {
    const lines = text.split("\n");
    return lines.map((line, idx) => {
      // Bullet points
      if (line.trim().startsWith("- ") || line.trim().startsWith("* ")) {
        const content = line.trim().substring(2);
        return (
          <li key={idx} className="ml-4 list-disc text-slate-300 text-xs my-1 font-sans leading-relaxed">
            {renderInlineFormatting(content)}
          </li>
        );
      }
      // Numbered lists
      const numMatch = line.trim().match(/^(\d+)\.\s+(.*)$/);
      if (numMatch) {
        const num = numMatch[1];
        const content = numMatch[2];
        return (
          <div key={idx} className="flex gap-1.5 text-xs text-slate-300 my-1 font-sans leading-relaxed pl-2">
            <span className="text-teal-400 font-mono font-bold">{num}.</span>
            <span>{renderInlineFormatting(content)}</span>
          </div>
        );
      }
      // Subheaders
      if (line.trim().startsWith("### ")) {
        return (
          <h4 key={idx} className="text-xs font-mono text-teal-400 font-bold uppercase tracking-wider mt-3 mb-1">
            {line.trim().substring(4)}
          </h4>
        );
      }
      if (line.trim().startsWith("## ")) {
        return (
          <h3 key={idx} className="text-xs font-sans text-white font-semibold mt-3 mb-1.5 border-b border-slate-800 pb-0.5">
            {line.trim().substring(3)}
          </h3>
        );
      }
      if (line.trim().startsWith("# ")) {
        return (
          <h2 key={idx} className="text-sm font-sans text-white font-extrabold mt-4 mb-2">
            {line.trim().substring(2)}
          </h2>
        );
      }
      if (line.trim() === "") {
        return <div key={idx} className="h-1.5" />;
      }
      return (
        <p key={idx} className="text-xs text-slate-300 leading-relaxed font-sans mb-1">
          {renderInlineFormatting(line)}
        </p>
      );
    });
  };

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col items-end pointer-events-none">
      {/* Absolute Chat Window Panel */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 30, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            transition={{ duration: 0.25, ease: 'easeOut' }}
            className="w-80 md:w-96 h-[500px] bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl flex flex-col overflow-hidden mb-4 pointer-events-auto"
            id="statutory-chat-box"
          >
            {/* Header Area */}
            <div className="bg-slate-950 border-b border-slate-800/80 px-4 py-3 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 bg-teal-500/10 border border-teal-500/30 rounded-xl flex items-center justify-center text-teal-400">
                  <Scale className="w-4 h-4 animate-pulse animate-duration-[3000ms]" />
                </div>
                <div>
                  <h3 className="text-xs font-sans font-extrabold text-white tracking-tight flex items-center gap-1">
                    Statutory AI Counsel
                    <span className="text-[8px] font-mono px-1.5 py-0.5 rounded-full bg-teal-500/10 text-teal-400 border border-teal-500/20 leading-none">
                      Active
                    </span>
                  </h3>
                  <p className="text-[9px] text-slate-500 font-mono tracking-wide uppercase leading-none mt-1">
                    Subject: {company.name}
                  </p>
                </div>
              </div>
              <button 
                onClick={() => setIsOpen(false)}
                className="w-6 h-6 rounded-lg text-slate-500 hover:text-slate-300 hover:bg-slate-900 flex items-center justify-center transition-all cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Notification / Context Header */}
            <div className="bg-slate-950/40 px-4 py-1.5 border-b border-slate-850 flex items-center justify-between text-[10px] font-mono text-slate-400">
              <span className="flex items-center gap-1 text-slate-500">
                <Bot className="w-3 h-3 text-teal-400/80" />
                Context synced
              </span>
              <span className="truncate max-w-[150px] text-teal-400 bg-teal-500/5 px-2 py-0.5 rounded-md border border-teal-500/10">
                {company.regNumber || "Pending Reg"}
              </span>
            </div>

            {/* Messages Body Scroll space */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-slate-900/40">
              {messages.length === 0 && (
                <div className="space-y-4 py-4">
                  {/* Default welcome card */}
                  <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 text-center">
                    <Sparkles className="w-6 h-6 text-teal-400 mx-auto mb-2.5 animate-bounce" />
                    <h4 className="text-xs font-sans font-bold text-white mb-1">
                      Bangladesh Companies Act AI Assistant
                    </h4>
                    <p className="text-[11px] text-slate-400 font-sans leading-relaxed">
                      Ask any questions concerning compliance thresholds, late fee calculations under RJSC guidelines, or how <strong>{company.name}</strong> can fix its active parameters.
                    </p>
                  </div>

                  {/* Quick-query Suggestion chips */}
                  <div className="space-y-1.5">
                    <p className="text-[9px] font-mono text-slate-500 uppercase tracking-widest leading-none pl-1 mb-2">
                      Suggested Consultations
                    </p>
                    <div className="flex flex-col gap-1.5">
                      {SUGGESTIONS.map((s, idx) => (
                        <button
                          key={idx}
                          onClick={() => handleSendMessage(s)}
                          className="w-full text-left bg-slate-950 hover:bg-slate-850 hover:border-slate-700 transition-all border border-slate-850 p-2.5 rounded-xl text-xs font-sans text-slate-300 flex items-start gap-2 group cursor-pointer"
                        >
                          <HelpCircle className="w-3.5 h-3.5 text-teal-500/60 mt-0.5 shrink-0 group-hover:text-teal-400" />
                          <span>{s}</span>
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {/* Message nodes */}
              {messages.map((msg, index) => (
                <div 
                  key={index}
                  className={`flex gap-2.5 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  {/* Assistant Avatar */}
                  {msg.role === 'assistant' && (
                    <div className="w-6 h-6 shrink-0 bg-slate-950 border border-slate-800 rounded-lg flex items-center justify-center text-teal-400">
                      <Bot className="w-3.5 h-3.5" />
                    </div>
                  )}

                  <div className="max-w-[80%] flex flex-col gap-1">
                    <div className={`px-3.5 py-2.5 rounded-2xl text-xs inline-block text-left ${
                      msg.role === 'user' 
                        ? 'bg-teal-500 text-slate-950 font-medium rounded-tr-sm' 
                        : 'bg-slate-950 border border-slate-850 text-slate-200 rounded-tl-sm'
                    }`}>
                      {msg.role === 'user' ? (
                        <p className="whitespace-pre-wrap">{msg.content}</p>
                      ) : (
                        <div className="space-y-1">
                          {formatMessageContent(msg.content)}
                        </div>
                      )}
                    </div>
                    <span className={`text-[8px] font-mono text-slate-500 px-1 leading-none ${
                      msg.role === 'user' ? 'text-right' : 'text-left'
                    }`}>
                      {msg.timestamp}
                    </span>
                  </div>

                  {/* User Avatar */}
                  {msg.role === 'user' && (
                    <div className="w-6 h-6 shrink-0 bg-teal-500/10 border border-teal-500/30 rounded-lg flex items-center justify-center text-teal-300">
                      <User className="w-3.5 h-3.5" />
                    </div>
                  )}
                </div>
              ))}

              {/* Pulsing skeleton loaders */}
              {isTyping && (
                <div className="flex gap-2.5 justify-start">
                  <div className="w-6 h-6 shrink-0 bg-slate-950 border border-slate-800 rounded-lg flex items-center justify-center text-teal-400">
                    <Bot className="w-3.5 h-3.5" />
                  </div>
                  <div className="bg-slate-950 border border-slate-850 px-3.5 py-3 rounded-2xl rounded-tl-sm max-w-[60%] flex gap-1.5 items-center">
                    <span className="w-1.5 h-1.5 bg-teal-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                    <span className="w-1.5 h-1.5 bg-teal-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                    <span className="w-1.5 h-1.5 bg-teal-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                  </div>
                </div>
              )}

              {/* Error messages banner */}
              {errorDetails && (
                <div className="bg-rose-500/10 border border-rose-500/20 text-rose-300 text-xs px-3.5 py-2.5 rounded-xl flex items-start gap-2 font-mono">
                  <AlertCircle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold">Compliance Fail-State:</span>
                    <p className="mt-1 text-[11px] text-rose-200/90 leading-normal">{errorDetails}</p>
                  </div>
                </div>
              )}

              <div ref={bottomRef} />
            </div>

            {/* Input Form area */}
            <form 
              onSubmit={(e) => {
                e.preventDefault();
                handleSendMessage(inputValue);
              }}
              className="bg-slate-950 border-t border-slate-800/80 p-3 flex gap-2"
            >
              <input
                ref={inputRef}
                type="text"
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                disabled={isTyping}
                placeholder={`Ask Act 1994 logic re: ${company.name}...`}
                className="flex-1 bg-slate-900 border border-slate-800 hover:border-slate-700 focus:border-teal-500 focus:outline-none rounded-xl px-3.5 py-2 text-xs text-slate-200 font-sans tracking-wide transition-all placeholder:text-slate-500"
              />
              <button
                type="submit"
                disabled={!inputValue.trim() || isTyping}
                className="w-9 h-9 bg-teal-500 hover:bg-teal-400 disabled:opacity-40 disabled:hover:bg-teal-500 text-slate-950 font-bold rounded-xl flex items-center justify-center transition-all cursor-pointer shadow-lg shadow-teal-500/10 active:scale-95 shrink-0"
              >
                <Send className="w-4 h-4" />
              </button>
            </form>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Floating circular toggle button widget */}
      <motion.button
        onClick={() => setIsOpen(!isOpen)}
        className="pointer-events-auto w-14 h-14 bg-gradient-to-tr from-slate-900 to-slate-800 hover:from-slate-800 hover:to-slate-700 border border-slate-700 text-teal-400 hover:text-teal-300 rounded-full flex items-center justify-center shadow-2xl hover:shadow-[0_0_20px_rgba(20,184,166,0.25)] hover:border-teal-500 transition-all transform active:scale-90 cursor-pointer relative"
        id="statutory-chat-trigger"
        whileTap={{ scale: 0.9 }}
      >
        <AnimatePresence mode="wait">
          {isOpen ? (
            <motion.div
              key="close"
              initial={{ rotate: -90, opacity: 0 }}
              animate={{ rotate: 0, opacity: 1 }}
              exit={{ rotate: 90, opacity: 0 }}
              transition={{ duration: 0.15 }}
            >
              <ChevronDown className="w-6 h-6 text-white" />
            </motion.div>
          ) : (
            <motion.div
              key="open"
              initial={{ rotate: 90, opacity: 0 }}
              animate={{ rotate: 0, opacity: 1 }}
              exit={{ rotate: -90, opacity: 0 }}
              transition={{ duration: 0.15 }}
              className="flex items-center justify-center"
            >
              <MessageSquare className="w-6 h-6 text-teal-400" />
            </motion.div>
          )}
        </AnimatePresence>

        {/* Floating status dot badge if unopened and no conversation started */}
        {!isOpen && messages.length === 0 && (
          <span className="absolute top-0.5 right-0.5 w-3.5 h-3.5 bg-teal-400 border-2 border-slate-900 rounded-full animate-bounce">
            <span className="absolute inset-0 bg-teal-400 rounded-full animate-ping opacity-75" />
          </span>
        )}
      </motion.button>
    </div>
  );
}
